# Generated by Django 3.2.3 on 2021-05-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('number_of_rooms', models.PositiveIntegerField(db_index=True, verbose_name='Кол-во комнат')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('room_class', models.CharField(choices=[('ECN', 'Эконом'), ('STD', 'Стандарт'), ('VIP', 'VIP')], db_index=True, max_length=10)),
            ],
        ),
    ]
