# Generated by Django 3.2.3 on 2021-05-25 11:15

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('ECN', 'Эконом'), ('STD', 'Стандарт'), ('VIP', 'VIP')], db_index=True, max_length=10, verbose_name='Класс номера'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2021, 5, 25, 14, 15, 22, 108669))])),
                ('ended_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.reservation', verbose_name='Бронь'),
        ),
    ]
