# Generated by Django 3.2.3 on 2021-05-25 11:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20210525_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='started_at',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.now)]),
        ),
    ]
