# Generated by Django 3.2.3 on 2021-05-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_reservation_started_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
