# Generated by Django 3.2.3 on 2021-06-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number_of_rooms',
            field=models.PositiveIntegerField(choices=[(2, '2-x'), (3, '3-x'), (4, '4-x')], db_index=True, verbose_name='Кол-во комнат'),
        ),
    ]
