# Generated by Django 3.2.3 on 2021-06-07 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0011_typeservice_usertypeservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertypeservice',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.RemoveField(
            model_name='typeservice',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ManyToManyField(related_name='room', through='hotel.Reservation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typeservice',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rated_services', through='hotel.UserTypeService', to=settings.AUTH_USER_MODEL),
        ),
    ]
