# Generated by Django 3.2.3 on 2021-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20210607_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeservice',
            name='count_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
