# Generated by Django 3.2.3 on 2021-06-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_typeservice_count_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeservice',
            name='count_rate',
            field=models.IntegerField(default=0),
        ),
    ]
