# Generated by Django 3.2.3 on 2021-06-08 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0014_alter_typeservice_count_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertypeservice',
            name='count_this_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertypeservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_type_service', to=settings.AUTH_USER_MODEL),
        ),
    ]
