# Generated by Django 3.2.3 on 2021-06-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
