# Generated by Django 3.2.3 on 2021-06-09 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_rename_created_at_message_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
    ]
