# Generated by Django 3.2.3 on 2021-06-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20210610_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
