# Generated by Django 3.2.3 on 2021-06-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_remove_room_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
    ]
