# Generated by Django 3.2.3 on 2021-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='ended_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
