# Generated by Django 3.2.3 on 2021-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_auto_20210614_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number_of_rooms',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], db_index=True, verbose_name='Кол-во комнат'),
        ),
    ]
