# Generated by Django 3.2.3 on 2021-06-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_room_number_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='last_message_today',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.message', verbose_name='Последнее сообщение за сегодня'),
        ),
    ]
